name: build-unit

on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  build-unit:
    name: build release unittest
    runs-on: ubuntu-latest
    container: westonortiz/goma-libs

    steps:
    - uses: actions/checkout@v2
    - name: info
      run: |
        mpirun -v
        cmake --version
    - name: configure
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -DENABLE_TESTING=ON .
    - name: build
      run: |
        cd build
        make -j 2
    - name: test
      run: |
        export OMPI_MCA_btl_base_warn_component_unused='0'
        cd build
        make -j2 
        ctest --output-on-failure -j 2
